---
- name: Ejecutar el comando ip a
  hosts: all


  tasks:
    - name: Ejecutar el comando ip a
      shell: |
        ip a
        ip route
      register: command_output
      changed_when: false

    - name: Mostrar la salida del comando ip a
      debug:
        msg: "{{ lookup ("command_output.stdout_lines") }}"
