---
- name: Ejecutar comandos de show ip
  hosts: fedora-server
  tasks:
    - name: Ejecutar los comandos "ip a" y "ip route"
      shell: |
        ip a && ip route
      register: command_output

    - name: Mostrar la salida de los comandos "ip a" y "ip route"
      debug:
        msg: "{{ command_output.stdout_lines }}"

