---
- name: Ejecutar el comando "ip a"
  hosts: all
  vars:
      commands:
      - "ip a"
      - "ip route"
  tasks:
    - name: Ejecutar el comando "ip a"
      ansible.builtin.shell: "{{ item }}"
      register: command_output
      with_items: "{{ commands }}"
      changed_when: false

    - name: Mostrar la salida del comando "ip a"
      debug:
        msg: "{{ command_output.stdout }}"
