---
- name: Ejecutar el comando ip a
  hosts: all

  tasks:
    - name: Ejecutar el comando ip a y ip route
      shell: |
        ip a && ip route
      register: command_output
      changed_when: false

    - name: Mostrar la salida del comando ip a
      debug:
        msg: "{{ command_output.stdout_lines }}"

    - name: Guardar la salida en un archivo temporal
      copy:
        content: "{{ command_output.stdout_lines | to_json }}"
        dest: "/tmp/{{ inventory_hostname }}_output.json"

- name: Recolectar resultados en localhost
  hosts: localhost
  tasks:
    - name: Crear directorio para resultados
      file:
        path: /root/outputs
        state: directory

    - name: Obtener archivos desde hosts remotos
      fetch:
        src: "/tmp/{{ inventory_hostname }}_output.json"
        dest: "/root/outputs/"
        flat: yes
