---
- name: Ejecutar el comando "ip a"
  hosts: all
   vars:
      commands:
      - "ip a"
      - "ip route"
  tasks:
    - name: Ejecutar el comando "ip a"
      register: command_output
      with_items: "{{ commands }}"
      changed_when: false

    - name: Mostrar la salida del comando "ip a"
      debug:
        var: ip_output.stdout
