---
- name: Ejecutar el comando ip a
  hosts: all

  tasks:
    - name: Ejecutar el comando ip a y ip route
      shell: |
        ip a && ip route
      register: command_output
      changed_when: false

    - name: Mostrar la salida del comando ip a
      debug:
        msg: "{{ command_output.stdout_lines }}"

    - name: Guardar la salida en un archivo temporal
      copy:
        content: "{{ command_output.stdout_lines | to_json }}"
        dest: "/tmp/{{ inventory_hostname }}_output.json"

- name: Recolectar y enviar resultados a fedora
  hosts: all
  tasks:
    - name: Crear directorio para resultados en fedora
      delegate_to: fedora
      file:
        path: /root/outputs
        state: directory
        
    - name: Enviar archivos a fedora
      delegate_to: fedora
      copy:
        src: "/tmp/{{ inventory_hostname }}_output.json"
        dest: "/root/outputs/{{ inventory_hostname }}_output.json"