---
- name: Ejecutar el comando ip a
  hosts: zabbix
  tasks:
    - name: Ejecutar el comando ip a y ip route
      shell: |
        ip a && ip route
      register: command_output
      changed_when: false

    - name: Mostrar la salida del comando ip a
      debug:
        msg: "{{ command_output.stdout_lines }}"
      when: "'zabbix' in group_names"

    - name: Almacenar salida en variable global
      set_fact:
        global_command_output: "{{ command_output.stdout_lines }}"

- name: Tareas en fedora linux
  hosts: fedora
  tasks:
    - name: Crear el directorio
      file:
        path: /root/outputs
        state: directory
      when: "'fedora' in group_names"

    - name: Guardar la salida en un archivo
      copy:
        content: "{{ hostvars['zabbix'][0].global_command_output | to_json }}"
        dest: "/root/outputs/{{ inventory_hostname }}_output.json"