---
- name: Ejecutar el comando ip a
  hosts: all

  tasks:
    - name: Ejecutar el comando ip a y ip route
      shell: |
        ip a && ip route
      register: command_output
      changed_when: false

    - name: Mostrar la salida del comando ip a
      debug:
        msg: "{{ command_output.stdout_lines }}"

    - name: Guardar la salida en un archivo
      delegate_to: 192.168.78.2
      file:
        path: /root/outputs
        state: directory
      copy:
        content: "{{ command_output.stdout_lines | to_json }}"
        dest: "/root/outputs/{{ inventory_hostname }}_output.json"