---
- name: Ejecutar comandos de red
  hosts: zabbix
  tasks:
    - name: Ejecutar los comandos "ip a" y "ip route"
      shell: |
        ip a && ip route
      register: network_output

    - name: Mostrar la salida de los comandos "ip a" y "ip route"
      debug:
        var: network_output.stdout

