---
- name: Ejecutar el comando ip a
  hosts: all
  vars:
      shell: |
        ip a
        ip route

  tasks:
    - name: Ejecutar el comando ip a
      register: command_output
      with_items: "{{ shell }}"
      changed_when: false

    - name: Mostrar la salida del comando ip a
      debug:
        msg: "{{ command_output.stdout_lines }}"
